# Config-version, do not change this.
Config-Version: 2.0

message:
  notplayer: "<red>You must be a player to do that!" # Only players can fly.
  no-permission: "<red>You do not have permission!" # No permission.
  invalidplayer: "<red>Invalid player." # Player not found.
  fly-on: "<yellow><bold>Flight <green><bold>enabled<yellow><bold>! <gray><italic>Watch your hunger." # Flight enabled.
  fly-off: "<yellow><bold>Flight <red><bold>disabled<yellow><bold>!" # Flight disabled.
  flyother-on: "<yellow><bold>Player flight <green><bold>enabled<yellow><bold>!" # Other player flight enabled.
  flyother-off: "<yellow><bold>Player flight <red><bold>disabled<yellow><bold>!" # Other player flight disabled.
  auto-disable: "<red>You got too hungry to fly. :(" # Flight disabled from hunger.
  lowhunger: "<red>You are too hungry to fly. :(" # Not enough hunger.
  targetlowhunger: "<red>Player cannot fly, they are too hungry." # Target not enough hunger.

  help:
    top: "<aqua><strikethrough>                                      "
    plugin: "<aqua><bold>HungryFlight"
    fly: "<green>/fly <yellow>Toggle your flight"
    flyother: "<green>/fly <player> <yellow>Toggle a player's flight"
    reload: "<green>/flyadmin reload <yellow>Reload config"
    bottom: "<aqua><strikethrough>                                      "

  adminhelp-reloadconfig: "<green>Configuration reloaded successfully!" # Reload message.
  adminhelp-invalid: "<red>Invalid command, type <yellow>/flyadmin <red>to view help." # Invalid command.

  Actionbar:
    enable: false # Enable actionbar.
    flying: "<green>Flight active, hunger draining."
    flying-nocosthunger: "<green>Flight active, no hunger cost."

settings:
  features:
    Costing:
      auto-disable: 6 # Hunger level to disable flight. 20 = full, 6 = 3 bars.
      Timer:
        enable: true # Enable hunger timer.
        time: 45 # Seconds between hunger costs.
      Interaction:
        enable: false # Enable interaction hunger costs.
        features:
          BlockBreak:
            enable: false # Charge hunger on block break.
            cost: 2
          BlockPlace:
            enable: false # Charge hunger on block place.
            cost: 2
          Attack:
            enable: false # Charge hunger on attack.
            cost: 2
          Damaged:
            enable: false # Charge hunger when damaged.
            cost: 2

  groups:
    default:
      FoodCost: 1 # Hunger cost.

    second:
      FoodCost: 1 # Hunger cost.
      Permission: "hungryflight.groups.second" # Group permission.

  permissions:
    fly: "hungryflight.fly"
    fly-other: "hungryflight.fly.other"
    no-hunger: "hungryflight.nohunger"
    admin-reload: "hungryflight.admin.reload"